branches:
  only:
    - master
secure: "iggaHCgZi9IZSKvoJGkEKpqXKxuJfFFJ53AB/Kx8veJRDfHDoHxF9NZwm3xsNJC6rYh3rQscF782kZW3cmB8y3XD2D029fouLwxiZXATS+NkzYWCa9KciQ0inGnfPzzAyBTOvpzjgNZ3H5A6xXjUSgjuwezd7KTQt8XSWdf4wSvu88BttC/f7IYRVhkdEtd1Jx1SBW990SUB+AByLKUBw/ReFi68u5GuEr0NmN1yaH+nnU8wbZuEajRBgVKsQPokadVOEpSX9zUEj7r0LlVc7FpOGqMfxOzVxxHlrIXqFRgwDMu6gLZSwAa6h54VuLBstEpEgcJBAzXAsWcBP+xOtfWV9blBkjmT9zVqmoyCwXCKFvElaQxnHj6MVJwM2hK02n1OP+wB9qsx0uCvlqYREcSqWpKvEbpJmU1F/J6UmJGe1JdcEqwlJqfpBvfxmWb1oWMM4/MZ4PxHSu4cm1RxA3vxD/gaYMlN+BaYQhv1y5bLUmCn2AQgguCGxlSBkH8qrjOz0gqsikeKuRXsE4hOmbslh79YsCEVFYgucK2zqdU4MD2qrqLetAt2QTLvXLgI4SLmG+f/Z8/gHT4RA6OFAtvNBX3xzQ+gl9IG1TYwE5UVfh0hgNRhqHM/nw1Hg8fTj9OhkfS2sQgk+apKetVJ+NE5M8JPROMSqShdOqYz25g="
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
- yarn test
script:
- ./build.sh
after_script:
- ./notify.sh
cache: yarn
deploy:
- provider: pages
  local-dir: docs
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
- provider: npm
  email: 171426589@qq.com
  api_key: $NPM_TOKEN
  skip-cleanup: true
