branches:
  only:
  - master
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
- yarn test
script:
- "./build.sh"
after_success:
- gem install dpl
after_script:
- "./notify.sh"
cache: yarn
deploy:
  matrix:
  - provider: pages
    local-dir: docs
    github-token:
      secure: AHdE/2s1iRvxfrWqd24GX9Ax7064Wow6g9tCgzTpDoGYEhelj866x2aEKa7fPt0ft2UJGDm4egjbezHZiLM3331tOMhOGu/a3DD1tuThUwItYXGr5rIL0Z2ZZI3KgcGKsGkdy7rCzKmjAylT4RjwaTaIO98gNRw9QbPtniF6c/CIQVYmYo6oN6IDcGytB5gU7ZypmIb3UkCaCwWp76428OxcSSL7iTuAqUHgWWL3bVCRho64ROG59LlKzF4gA6joX45oZl/bNa5ct9cr1P1zMSpzkveMoiZ9ZVK7g0oIztQb/I2NOk2XDjgq/yhMSUCwF3BLd9TaB8U4g1+0zT6avv5cOukaM3pq94IwZjkPmhMYJ/qllYdVtV9ghChNcVi6kJsPvXUyk7pnuSLfX306BPneOcVwF8/WD6DtoZtYmCpZ6FJfQF6IwUpOsMT8fa3Cv1PNIbuhHhJachha3+/1dughsuNSnIGHIOm0P/t9Qx+y6Zei2VQAAL98jVDfKIt1/ho7aRdERXd2/qNZxaG5ApmuAxfdUSaepn2WmuVqZwqdG+G5PEtdHTEv73m//Lv/Qo/GXB6MUl+DjNCsWiL2BLdyZydYkRdfiiikxQeKZRxlf4Y8zdsIUhpGb48HKAvA+GUNtBVDmsQt/2TvqcK6TiC4w0kS/OJOKAblfL7A/x0=
    skip-cleanup: true
    keep-history: true
  - provider: npm
    email: 171426589@qq.com
    skip-cleanup: true
    api_key:
      - secure: N+Nobb/OzKc++q23K+L8KykNz0bLQfzqe56pnJg/40FuhIySIhSbZxOI11p4YalMJvCTXhdv4CrJKtAArqW79oY2aiYOtr5zNTbnxyp8ODnuZVNFZ3aE7dsJjigawvin7NzGT9RbUOX+S+Va92oanjAhUi4YttjYBaRn/dggkb51+HV85rusHt4WtgQ8FT76FEPI/4ciPfe+FEvG3rje0WQziorv6L2XL6842AUJwe72PYzsZm1yln0SEDGyTZ5Cf6zmNBOKxnXKJAO8TBaxgh3pMJHudmlUsreXiz/0JCF0FWEckY7Lc/+VqO/mQYo0878zLKBKH/iqrvM/eWIZGCqmtdXEm4MCF1u9iI3Xu8Zq+5St25VBdq8lc55mtqJQth1WhSuOZ+qlnE3DBmqqZPZWdCUiNFMrnJ7iBpqx1kgpn2xg13/Rl+WUTKNg+0HVRElJFf50TEdI8GBeAXduL0hvzf3rYR8pGsGiNmdDtFemPzJtsgRR5I6HJow5tVP0yOP1aIEAEucwXRs+DPImNfPIuqGrW94Ts/j9eI6UZdzmoSX9VAGMmcBY31iqydOhdbcYeAw3+6/GhrimTzokzZN32jP9ExvQgsKg1BzgGI92Zw0LfyViJMOu87RxKvTca++yA0lfDrpG+QiFwn9/p9HJ7VmedOCHuBtRGJwBbDs=
